### ISSUE TITLE
Audio player not working

### ISSUE THREAD

**Issue by happywolf** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima-Legacy#1]
I noticed when I tried playing any type of sound. The sound player disappears and there is no audio coming. I tried with and without modules.

**Comment by spyrella** [comment]
The sound player is usually handled by the foundry application, not the system. If I may ask, what version of foundry are you using, and if you can try playing audio on another system.

**Comment by happywolf** [comment]
The sound player worked on other game systems so that's why I thought maybe it was the game system itself. But I am using V11 Build 314

**Comment by happywolf** [comment]
I now updated to the current Foundry update in hope it might work. But same thing still happens, it flickers real quick out of existence and no music can be played

**Comment by spyrella** [comment]
Issue has been resolved on discord channel.

Solution: problem occurred due to how modules automatically imported music. Manually importing music resolved this issue.
